# Generated by Django 4.2 on 2023-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='another_field',
            field=models.CharField(choices=[('profile', 'tester'), ('profile2', 'developer')], default='DEFAULT', max_length=250),
        ),
    ]
